# Python libraries

In [3]:
 # creating an one dimensional array
import numpy as np
x=numpy.array([1,2,3,4])
print(x)


[1 2 3 4]


In [4]:
type(x)

numpy.ndarray

In [54]:
y=numpy.array([[1,2,3],[3,5,7]]

TypeError: only integer scalar arrays can be converted to a scalar index

In [9]:
# creating 3 dimensional array
import numpy as np
z=np.array([[1,2],[3,4],[5,6]])
print(z)

[[1 2]
 [3 4]
 [5 6]]


In [144]:
print(np.amin(z,0))
a=([[1,2],[5,3],[3,4]])

b=np.array([1,2], dtype=complex)
print(b)

[1 2]
[1.+0.j 2.+0.j]


## b[1][0]

In [23]:
z.shape

(3, 2)

In [24]:
z.size

6

In [89]:
import numpy
p=numpy.arange(10)
p

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# ARRAY slicing

In [111]:
p[:5]

array([0, 1, 2, 3, 4])

In [112]:
p[0::2]

array([0, 2, 4, 6, 8])

In [113]:
p[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [114]:
p[9:0]

array([], dtype=int32)

In [115]:
p[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# finding  shape,size,dimensions

In [119]:
n=([[1,2,5],[5,3,9],[3,4,3]])
s=np.array(n)
s.shape


(3, 3)

In [120]:
s.size

9

In [121]:
s.ndim

2

# Reshape

In [122]:
r=np.arange(1,17).reshape(4,4)
print(r)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


# cancatenation of arrays

In [123]:
a1=np.array([1,2,3])
b1=np.array([5,6,7])
c1=np.concatenate([a1,b1])
print(c1)

[1 2 3 5 6 7]


In [124]:
c1[2]+c1[5]

10

# split

In [125]:
d=[1,2,3,4,5,6,7,8,9,10]
d1,d2,d3=np.split(d,[3,4])
print(d1,d2,d3)

[1 2 3] [4] [ 5  6  7  8  9 10]


In [103]:
g1=np.arange(100).reshape(10,10)
print(g1)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [104]:
g2=np.arange(45).reshape(5,9)
g2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44]])

In [105]:
g3=np.ones((2,2))
print(g3)

[[1. 1.]
 [1. 1.]]


In [106]:
g3=g3+5
print(g3)

[[6. 6.]
 [6. 6.]]


In [107]:
g3=g3-4
g3

array([[2., 2.],
       [2., 2.]])

In [108]:
g4=[2,5,8]
h=np.array(g4)
print(np.sqrt(h))
print(np.sin(h))
print(np.cos(h))
print(np.tan(h))
print(np.log(h))

[1.41421356 2.23606798 2.82842712]
[ 0.90929743 -0.95892427  0.98935825]
[-0.41614684  0.28366219 -0.14550003]
[-2.18503986 -3.38051501 -6.79971146]
[0.69314718 1.60943791 2.07944154]


In [126]:
g=np.arange(10000)
print(g)

[   0    1    2 ... 9997 9998 9999]


In [127]:
g5=np.random.rand(2,5)
print(g5)

[[0.2521718  0.70805695 0.27107395 0.07742138 0.16529188]
 [0.20989705 0.10268669 0.84229308 0.71467238 0.61169906]]


In [128]:
g6=np.random.randint(2,size=5)
print(g6)

[1 0 0 1 0]


In [130]:
g7=np.random.randf(2)
print(g7)

AttributeError: module 'numpy.random' has no attribute 'randf'

In [131]:
print(dir(numpy))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

In [132]:
print(len(dir(np)))

620


In [135]:
print(np.__version__)

1.19.2


In [136]:
print("hello")

hello


# FILTERING ARRAYS

In [ ]:
import numpy as np
a=np.array[1,2,3]
#print a



In [138]:
a=np.array([1,2,3,4,5])
filter_a=a%2==0
new_a=a[filter_a]
print(filter_a)
print(new_a)

[False  True False  True False]
[2 4]


In [ ]:
creating filtering element 

In [139]:
a=np.array([1,2,3,4,5])
filter_a=a%2!=0
new_a=a[filter_a]
print(filter_a)
print(new_a)



[ True False  True False  True]
[1 3 5]


In [140]:
print(np.amax(a))

5


In [147]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [148]:
print(np.amin(a,1))

[1 4 7]


In [149]:
print(np.amax(a,1))

[3 6 9]


In [150]:
print(np.amin(a,0))

[1 2 3]


In [151]:
print(np.amax(a,0))

[7 8 9]
