# pANDAS

 # 2 mechanisms
- SERIES
- DATA FRAMES

In [5]:
import pandas as pd

In [6]:
pd.__version__


'1.1.3'

In [7]:
print(dir(pd))

['BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Float64Index', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int64Index', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt64Index', 'UInt8Dtype', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_config', '_hashtable', '_is_numpy_dev', '_lib', '_libs', '_np_version_under1p16', '_np_version_under1p17', '_np_version_under1p18', '_testing', '_tslib', '_typing', '_version', 'api', 'array', 'arrays', 'bdate_range', 'comp

In [8]:
print(len(dir(pd)))

140


In [13]:
import numpy as np
import pandas as pd

In [55]:
r=pd.Series(np.array([1,4,6,8,4]),index=['a','b','c','d','e'],name='rollno',dtype='float')

In [56]:
r

a    1.0
b    4.0
c    6.0
d    8.0
e    4.0
Name: rollno, dtype: float64

In [14]:
data=np.arange(30,100,10)
print(data)

[30 40 50 60 70 80 90]


In [52]:
help(np)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [17]:
a=pd.Series(data)
print(a)

0    30
1    40
2    50
3    60
4    70
5    80
6    90
dtype: int32


In [26]:
a.name="population"
a.name

'population'

In [25]:
a.dtype

dtype('int32')

In [27]:
a[1:7:2]

1    40
3    60
5    80
Name: population, dtype: int32

In [28]:
a[: : 3]

0    30
3    60
6    90
Name: population, dtype: int32

In [30]:
a.values

array([30, 40, 50, 60, 70, 80, 90])

In [32]:
type(a.values)

numpy.ndarray

In [33]:
a.index

RangeIndex(start=0, stop=7, step=1)

In [37]:
a.index=['Bana','seema','divu','amu','bommi','commu','dammu']

In [39]:
print(a)

Bana     30
seema    40
divu     50
amu      60
bommi    70
commu    80
dammu    90
Name: population, dtype: int32


In [61]:
b={'Bana': 99,'seema': 98,'divu': 101,'amu': 60,'bommi': 70,'commu': 80,'dammu':90}
b.items()

dict_items([('Bana', 99), ('seema', 98), ('divu', 101), ('amu', 60), ('bommi', 70), ('commu', 80), ('dammu', 90)])

In [60]:
pd.Series(b,name='Data of students with marks')

Bana      99
seema     98
divu     101
amu       60
bommi     70
commu     80
dammu     90
Name: Data of students with marks, dtype: int64

In [46]:
b['Bana']

30

In [64]:
b['divu']


101

In [70]:
a.iloc[3:6]

amu      60
bommi    70
commu    80
Name: population, dtype: int32

In [68]:
a.loc['Bana']

30

In [73]:
c=pd.Series(np.array([9,4,5,6,7]),index=list('ABCDE'),name='Grades')
print(c)

A    9
B    4
C    5
D    6
E    7
Name: Grades, dtype: int32


In [75]:
c>5

A     True
B    False
C    False
D     True
E     True
Name: Grades, dtype: bool

In [76]:
c[c>6]

A    9
E    7
Name: Grades, dtype: int32

In [77]:
c*10

A    90
B    40
C    50
D    60
E    70
Name: Grades, dtype: int32

# statisticals functions

In [80]:
c.mean()

6.2

In [82]:
c['A':'C'].mean()

6.0

In [86]:
c%10

A    9
B    7
C    5
D    6
E    7
Name: Grades, dtype: int32

In [87]:
c['B']=7

In [88]:
c

A    9
B    7
C    5
D    6
E    7
Name: Grades, dtype: int32

# Data Frames

In [118]:
import pandas as pd
s_marks={'sub1':[92,96,93,95,98,57],
         'sub2':[98,90,95,90,69,88],
         'sub3':[87,78,94,56,98,79]}

In [119]:
marks=pd.DataFrame(s_marks,index=['Bana','divya','seema','Bommi','manasa','nirupa'])
marks


sub1  sub2  sub3
Bana      92    98    87
divya     96    90    78
seema     93    95    94
Bommi     95    90    56
manasa    98    69    98
nirupa    57    88    79

In [120]:
marks.loc['Bana'].sum()

277

In [121]:
marks.index

Index(['Bana', 'divya', 'seema', 'Bommi', 'manasa', 'nirupa'], dtype='object')

In [122]:
marks.columns

Index(['sub1', 'sub2', 'sub3'], dtype='object')

In [123]:
marks.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, Bana to nirupa
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   sub1    6 non-null      int64
 1   sub2    6 non-null      int64
 2   sub3    6 non-null      int64
dtypes: int64(3)
memory usage: 352.0+ bytes


In [124]:
marks.size

18

In [125]:
marks.shape

(6, 3)

In [126]:
marks.describe()

sub1       sub2       sub3
count   6.000000   6.000000   6.000000
mean   88.500000  88.333333  82.000000
std    15.578832  10.171857  15.006665
min    57.000000  69.000000  56.000000
25%    92.250000  88.500000  78.250000
50%    94.000000  90.000000  83.000000
75%    95.750000  93.750000  92.250000
max    98.000000  98.000000  98.000000

In [127]:
marks[['sub1','sub2']]

sub1  sub2
Bana      92    98
divya     96    90
seema     93    95
Bommi     95    90
manasa    98    69
nirupa    57    88

In [131]:
marks[marks>70]

sub1  sub2  sub3
Bana    92.0  98.0  87.0
divya   96.0  90.0  78.0
seema   93.0  95.0  94.0
Bommi   95.0  90.0   NaN
manasa  98.0   NaN  98.0
nirupa   NaN  88.0  79.0

In [142]:
marks.sub1['seema']

93

In [145]:
marks.sub2['Bana']

98

In [148]:
marks.iloc[4][2]

98

In [153]:
marks['sub4']=[67,89,99,78,90,54]

In [154]:
marks

sub1  sub2  sub3  sub4
Bana      92    98    87    67
divya     96    90    78    89
seema     93    95    94    99
Bommi     95    90    56    78
manasa    98    69    98    90
nirupa    57    88    79    54

# how to drop columns

In [156]:
marks.drop(columns='sub1')

sub2  sub3  sub4
Bana      98    87    67
divya     90    78    89
seema     95    94    99
Bommi     90    56    78
manasa    69    98    90
nirupa    88    79    54

In [157]:
marks

sub1  sub2  sub3  sub4
Bana      92    98    87    67
divya     96    90    78    89
seema     93    95    94    99
Bommi     95    90    56    78
manasa    98    69    98    90
nirupa    57    88    79    54

## permanently deleting 

In [172]:
marks.drop(columns='sub2',inplace=True)

In [173]:
marks

sub3  sub4
Bana      87    67
divya     78    89
seema     94    99
Bommi     56    78
manasa    98    90
nirupa    79    54

In [174]:
marks['sub5']=[67,89,99,78,90,54]

In [175]:
marks

sub3  sub4  sub5
Bana      87    67    67
divya     78    89    89
seema     94    99    99
Bommi     56    78    78
manasa    98    90    90
nirupa    79    54    54

In [177]:
marks.drop('Bommi',inplace=True)

In [178]:
marks

sub3  sub4  sub5
Bana      87    67    67
divya     78    89    89
seema     94    99    99
manasa    98    90    90
nirupa    79    54    54

# updating

In [180]:
marks.iloc[4][1]=98

In [181]:
marks

sub3  sub4  sub5
Bana      87    67    67
divya     78    89    89
seema     94    99    99
manasa    98    90    90
nirupa    79    98    54

In [195]:
marks['sub4']=100
marks

sub3  sub4  sub5
Bana       0   100     0
divya      0   100     0
seema      0   100     0
manasa     0   100     0
nirupa    79   100    54

In [196]:
marks


sub3  sub4  sub5
Bana       0   100     0
divya      0   100     0
seema      0   100     0
manasa     0   100     0
nirupa    79   100    54

In [200]:
marks.iloc[1:0]=99

In [201]:
marks

sub3  sub4  sub5
Bana       0   100     0
divya      0   100     0
seema      0   100     0
manasa     0   100     0
nirupa    79   100    54

In [226]:
import pandas as pd



In [227]:
#reading the csv file using read_csv
data=pd.read_csv('population.csv')


In [228]:
data

2001   2002  2003  2004   2005  2006  2007  2008  2009   2010
0     91   91.5    90    95   92.0    96    98    95    92   97.6
1    120  121.9   123   125  122.6   131   142   134   134  120.0
2     91   91.5    90    95   92.0    96    98    95    92   97.6
3    120  121.9   123   125  122.6   131   142   134   134  120.0
4     91   91.5    90    95   92.0    96    98    95    92   97.6
5    120  121.9   123   125  122.6   131   142   134   134  120.0
6     91   91.5    90    95   92.0    96    98    95    92   97.6
7    120  121.9   123   125  122.6   131   142   134   134  120.0
8     91   91.5    90    95   92.0    96    98    95    92   97.6
9    120  121.9   123   125  122.6   131   142   134   134  120.0
10    91   91.5    90    95   92.0    96    98    95    92   97.6
11   120  121.9   123   125  122.6   131   142   134   134  120.0

In [229]:
data.shape


(12, 10)

In [230]:
data.size

120

In [231]:
data.index

RangeIndex(start=0, stop=12, step=1)

In [232]:
data.values

array([[ 91. ,  91.5,  90. ,  95. ,  92. ,  96. ,  98. ,  95. ,  92. ,
         97.6],
       [120. , 121.9, 123. , 125. , 122.6, 131. , 142. , 134. , 134. ,
        120. ],
       [ 91. ,  91.5,  90. ,  95. ,  92. ,  96. ,  98. ,  95. ,  92. ,
         97.6],
       [120. , 121.9, 123. , 125. , 122.6, 131. , 142. , 134. , 134. ,
        120. ],
       [ 91. ,  91.5,  90. ,  95. ,  92. ,  96. ,  98. ,  95. ,  92. ,
         97.6],
       [120. , 121.9, 123. , 125. , 122.6, 131. , 142. , 134. , 134. ,
        120. ],
       [ 91. ,  91.5,  90. ,  95. ,  92. ,  96. ,  98. ,  95. ,  92. ,
         97.6],
       [120. , 121.9, 123. , 125. , 122.6, 131. , 142. , 134. , 134. ,
        120. ],
       [ 91. ,  91.5,  90. ,  95. ,  92. ,  96. ,  98. ,  95. ,  92. ,
         97.6],
       [120. , 121.9, 123. , 125. , 122.6, 131. , 142. , 134. , 134. ,
        120. ],
       [ 91. ,  91.5,  90. ,  95. ,  92. ,  96. ,  98. ,  95. ,  92. ,
         97.6],
       [120. , 121.9, 123. , 125. , 122.6, 

In [233]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   2001    12 non-null     int64  
 1   2002    12 non-null     float64
 2   2003    12 non-null     int64  
 3   2004    12 non-null     int64  
 4   2005    12 non-null     float64
 5   2006    12 non-null     int64  
 6   2007    12 non-null     int64  
 7   2008    12 non-null     int64  
 8   2009    12 non-null     int64  
 9   2010    12 non-null     float64
dtypes: float64(3), int64(7)
memory usage: 1.1 KB


In [235]:
data.index=['India','China','Japan','Bangladesh','Kochin','Africa','USA','Butan','Nepal','Russia','Mynmar','Singapore']

In [236]:
data

2001   2002  2003  2004   2005  2006  2007  2008  2009   2010
India         91   91.5    90    95   92.0    96    98    95    92   97.6
China        120  121.9   123   125  122.6   131   142   134   134  120.0
Japan         91   91.5    90    95   92.0    96    98    95    92   97.6
Bangladesh   120  121.9   123   125  122.6   131   142   134   134  120.0
Kochin        91   91.5    90    95   92.0    96    98    95    92   97.6
Africa       120  121.9   123   125  122.6   131   142   134   134  120.0
USA           91   91.5    90    95   92.0    96    98    95    92   97.6
Butan        120  121.9   123   125  122.6   131   142   134   134  120.0
Nepal         91   91.5    90    95   92.0    96    98    95    92   97.6
Russia       120  121.9   123   125  122.6   131   142   134   134  120.0
Mynmar        91   91.5    90    95   92.0    96    98    95    92   97.6
Singapore    120  121.9   123   125  122.6   131   142   134   134  120.0

In [240]:
gist=pd.read_excel('gist_4-1.xlsx')
gist

Unnamed: 0  Information security  Mobile deveopment  Grid computing  \
0      Bhavana                    53                 56              53   
1     Thasleem                    42                 45              42   
2   Divya sree                    63                 52              63   
3       Manasa                    41                 65              41   
4       Nirupa                    52                 75              52   
5       Reshma                    65                 42              65   
6  Meghalavani                    45                 36              45   
7      Vandana                    65                 65              65   
8      Divya                      61                 25              61   
9      Vennela                    45                 35              45   

   software architecture  Software management  Management sceince  
0                     56                   53                  56  
1                     45                   42                  45  
2                     52                   63                  52  
3                     65                   41                  65  
4                     75                   52                  75  
5                     42                   65                  42  
6                     36                   45                  36  
7                     65                   65                  65  
8                     25                   61                  25  
9                     35                   45                  35